### ISSUE TITLE
Bug: The attached audio is displayed over the header when scrolling

### ISSUE THREAD

**Issue by unaimillan** [provodach/frontend-v4#5]
On the main page, attached audio files from the feed are not covered by header(player) and continue to be rendered when the page is scrolled
> ![Безымянный](https://user-images.githubusercontent.com/12885904/61322057-89220b00-a815-11e9-910e-d6f5a7f8ac49.png)

**Comment by namikiri** [comment]
Thank you for your report, Mike!

It's a Chrome/Chromium-based browsers issue.

We'll investigate and fix it ASAP.

**Comment by namikiri** [comment]
Fixed in commit 3ab313e, thanks for reporting :3
